I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 129, in script
    "{i}The shopkeeper returns [(amt - cost):.2f] dollars to you.{/i}"
KeyError: u'(amt - cost)'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 129, in script
    "{i}The shopkeeper returns [(amt - cost):.2f] dollars to you.{/i}"
  File "/Applications/renpy-7.4.8-sdk/renpy/ast.py", line 721, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "/Applications/renpy-7.4.8-sdk/renpy/exports.py", line 1417, in say
    who(what, *args, **kwargs)
  File "/Applications/renpy-7.4.8-sdk/renpy/character.py", line 1222, in __call__
    what = self.prefix_suffix("what", self.what_prefix, what, self.what_suffix)
  File "/Applications/renpy-7.4.8-sdk/renpy/character.py", line 1141, in prefix_suffix
    return (sub(prefix) + sub(body) + sub(suffix))
  File "/Applications/renpy-7.4.8-sdk/renpy/character.py", line 1121, in sub
    return renpy.substitutions.substitute(s, scope=scope, force=force, translate=translate)[0]
  File "/Applications/renpy-7.4.8-sdk/renpy/substitutions.py", line 270, in substitute
    s = formatter.vformat(s, (), kwargs)
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/string.py", line 563, in vformat
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/string.py", line 585, in _vformat
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/string.py", line 646, in get_field
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/string.py", line 605, in get_value
KeyError: u'(amt - cost)'

Darwin-20.6.0-x86_64-i386-64bit
Ren'Py 7.4.9.2142
KLOQOWEJ 1.0
Wed Oct 20 06:31:35 2021
